#!/bin/bash
# PostToolUse (Bash) check: did `db:generate` actually produce a migration?
#
# Automates Database Rule 8(a)/(b): after drizzle-kit generate, a new .sql
# file must exist in src/db/migrations/ and follow the NNNN_*.sql naming
# convention that migrate.ts's readdirSync discovery depends on. Agents have
# assumed generated migrations would be discovered when they weren't.
#
# Exit 0 = silent. Exit 2 = stderr is fed back to the agent (nothing blocked;
# the generate already ran).

set -uo pipefail

INPUT=$(cat)
CMD=$(printf '%s' "$INPUT" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("tool_input",{}).get("command",""))' 2>/dev/null || echo "")

[ -z "$CMD" ] && exit 0

# Only react to migration-generating commands.
printf '%s' "$CMD" | grep -qE 'npm[[:space:]]+run[[:space:]]+db:generate|drizzle-kit[[:space:]]+generate' || exit 0

MIGRATIONS_DIR="src/db/migrations"

if [ ! -d "$MIGRATIONS_DIR" ]; then
  echo "WARNING: $MIGRATIONS_DIR does not exist after db:generate — the migration
was NOT created where migrate.ts discovers files (Database Rule 8)." >&2
  exit 2
fi

# A migration generated by this command should have an mtime within the last
# two minutes. -mmin is portable across BSD (macOS) and GNU find.
RECENT=$(find "$MIGRATIONS_DIR" -maxdepth 1 -name '*.sql' -mmin -2 2>/dev/null)

if [ -z "$RECENT" ]; then
  echo "WARNING: db:generate ran but no new .sql file appeared in $MIGRATIONS_DIR
within the last 2 minutes. Either the schema had no changes (fine — confirm
that was expected) or generation failed silently. Database Rule 8: never
assume a generated migration was discovered without verifying it." >&2
  exit 2
fi

# Naming convention: migrate.ts discovers NNNN_*.sql only.
BAD=$(printf '%s\n' "$RECENT" | while IFS= read -r f; do
  base=$(basename "$f")
  printf '%s' "$base" | grep -qE '^[0-9]{4}_.+\.sql$' || echo "$base"
done)

if [ -n "$BAD" ]; then
  echo "WARNING: new migration file(s) do not match the NNNN_*.sql naming convention
migrate.ts requires (Database Rule 8b): $BAD
Rename to match (e.g. 0007_description.sql) or migrate.ts will skip them." >&2
  exit 2
fi

# Success path: nudge the remaining verification step without blocking.
echo "Migration file generated: $(printf '%s\n' "$RECENT" | xargs -n1 basename | tr '\n' ' ')
Remaining per Database Rule 8c: run 'npm run db:migrate' against your dev branch to
confirm it executes." >&2
exit 2
