#!/bin/bash
# CASA SAQ Auto-Fill Script
# Each question has a "Yes" button ref and a textbox ref
# Pattern: Yes button, textbox, Yes button, textbox, ...

CLI="npx @playwright/cli -s=antigravity_ui"
DELAY=0.3

# Arrays: yes_refs[i] = Yes button for Q(i+1), text_refs[i] = textbox for Q(i+1)
yes_refs=(e215 e233 e251 e269 e287 e305 e323 e341 e359 e377 e395 e413 e431 e449 e467 e485 e503 e521 e539 e557 e575 e593 e611 e629 e647 e665 e683 e701 e719 e737 e755 e773 e791 e809 e827 e845 e863 e881 e899 e917 e935 e953 e971 e989 e1007 e1025 e1043 e1061 e1079 e1097 e1115 e1133 e1151 e1169)
text_refs=(e222 e240 e258 e276 e294 e312 e330 e348 e366 e384 e402 e420 e438 e456 e474 e492 e510 e528 e546 e564 e582 e600 e618 e636 e654 e672 e690 e708 e726 e744 e762 e780 e798 e816 e834 e852 e870 e888 e906 e924 e942 e960 e978 e996 e1014 e1032 e1050 e1068 e1086 e1104 e1122 e1140 e1158 e1176)

# Answers array - one per question
answers=(
"FGAC.ai's architecture has documented trust boundaries. The system consists of: (1) a Next.js frontend hosted on Vercel serving the dashboard UI; (2) a serverless API proxy layer (Vercel Edge Functions) that enforces fine-grained access rules; (3) Clerk as the managed authentication/identity provider handling Google OAuth; (4) Neon Serverless PostgreSQL for storing user metadata, proxy keys, access rules, and delegation records. Data flows: AI Agents authenticate via Bearer token, API proxy validates key, evaluates access rules against the database, proxy injects the real Google OAuth token (sourced from Clerk's token vault), forwards the request to Google APIs, applies response filtering (regex blacklists/whitelists), and returns the sanitized response. Google user data (email content) is never persisted; it flows through memory only."
"The application uses no deprecated client-side technologies. The frontend is built with React 19 (Next.js 16), standard HTML5, CSS, and modern JavaScript. No plugins, Flash, ActiveX, Silverlight, or Java applets are used."
"All access control is enforced server-side in our Vercel Edge Functions. The proxy route handler (/api/proxy/[...path]/route.ts) performs: (1) Bearer token authentication against the database, (2) key revocation/expiration checks, (3) email delegation authorization, (4) fine-grained rule evaluation (read blacklists, send whitelists, label filters, deletion guards). No access control decisions are made on the client."
"Sensitive data is classified as follows: Critical - Google OAuth access tokens (managed exclusively by Clerk; never stored in our database), proxy key secrets (sk_proxy_*). Confidential - User email addresses, access rule configurations, delegation records. Public - Landing page content, setup documentation, SKILL.md files. All critical data is encrypted in transit (TLS) and at rest (Neon PostgreSQL encryption)."
"Protection requirements by level: Critical data - encrypted at rest (Neon), encrypted in transit (TLS 1.2+), never logged, access audited. Confidential data - encrypted at rest, encrypted in transit, accessible only by authenticated users through Clerk session tokens. Public data - served over HTTPS with security headers (X-Frame-Options: DENY, CSP: frame-ancestors 'none', X-Content-Type-Options: nosniff). We enforce a zero-data-retention policy for Gmail message content."
"All application code is deployed through our CI/CD pipeline via GitHub to Vercel, which provides immutable, content-hashed deployment artifacts. JavaScript bundles are served from Vercel's CDN with content-addressed filenames. The only external script is the Clerk authentication SDK, loaded from Clerk's managed CDN - a trusted, SOC 2 Type II certified authentication provider. All npm dependencies are audited via npm audit and locked via package-lock.json."
"The application uses two subdomains: fgac.ai (primary) and gmail.fgac.ai (API proxy). Both are managed through Cloudflare DNS with active monitoring. Cloudflare's proxy mode provides protection against subdomain takeover. The Vercel deployment is permanently attached to the project and cannot be orphaned."
"The application does not accept file uploads. The API proxy forwards Gmail API requests which are bounded by Google's own size limits. Next.js API routes enforce a default body parser limit of 1MB. The proxy handler reads request bodies only for POST requests (email send) and does not store them."
"The application does not accept or store files from untrusted sources. All file serving is limited to static assets (logos, SKILL.md configuration files) bundled at build time in the public directory. No user-uploaded files are stored on the server."
"The application does not accept file uploads from users. All served content is static assets bundled at build time. The proxy forwards Gmail API responses (JSON) without storing files. No file upload functionality exists in the application."
"API keys are transmitted exclusively in the Authorization: Bearer HTTP header, never in URLs. Session tokens are managed by Clerk and transmitted via secure, HttpOnly cookies. No sensitive data appears in URL paths or query parameters."
"Authorization is enforced at two layers: (1) Route level - Clerk middleware (src/middleware.ts) protects /dashboard routes via auth.protect(), redirecting unauthenticated users. (2) Resource level - The proxy handler performs per-request authorization: key validation, email-level access checks via keyEmailAccess table, delegation verification, and fine-grained rule evaluation before any data reaches the requesting agent."
"The proxy explicitly handles only GET, POST, and DELETE methods. DELETE requests are further restricted: permanent email deletion (trash/emptyTrash) is globally blocked by a hardcoded safeguard in the proxy handler. The API CORS configuration restricts allowed methods with origin limited to https://fgac.ai."
"The application uses a fully automated CI/CD pipeline: GitHub to Vercel. Every push to main triggers an automated production build and deployment. Preview deployments are created for every branch/PR. Dependencies are locked via package-lock.json, and Vercel provides immutable deployment artifacts. Environment variables are scoped per environment."
"Full redeployment takes under 60 seconds via Vercel's automated pipeline. Database schema migrations are managed via Drizzle ORM with versioned SQL migration files. Neon PostgreSQL provides automated backups and point-in-time recovery."
"All security-relevant configuration is version-controlled in Git (security headers in next.config.ts, middleware rules in src/middleware.ts, access control logic in API route handlers). Any changes require a Git commit with full authorship and timestamp history. Environment variables are managed through Vercel's dashboard."
"Next.js production builds automatically disable all debug features, source maps, and development-only warnings. NODE_ENV is set to production in the Vercel production environment. Error responses return generic messages only without stack traces."
"The application does not use the Origin header for authentication or access control. Authentication is performed via Bearer tokens (proxy keys validated against the database) and Clerk session tokens (validated via Clerk's server-side SDK). CORS headers are set for browser security but are not used as an access control mechanism."
"User authentication is managed entirely by Clerk. Clerk enforces configurable password policies including minimum length requirements. The primary authentication method is Google OAuth (passwordless). For email/password authentication, Clerk's password policy enforces minimum complexity requirements."
"Our application does not generate initial passwords - authentication is handled by Clerk via Google OAuth. System-generated secrets (proxy keys, sk_proxy_*) are generated using Node.js crypto.randomBytes() producing 32-byte cryptographically random values (64 hex characters). These keys support optional TTL and can be revoked at any time."
"Our application does not directly store passwords. All password management is delegated to Clerk, which stores passwords using bcrypt with per-user salts, resistant to offline attacks. Proxy key secrets are generated with 256 bits of entropy and can be revoked/rotated at any time."
"The application has no shared or default accounts. Every user authenticates via their individual Google account through Clerk's OAuth flow. The database has no seeded admin accounts. Database credentials are unique per environment and managed through Vercel environment variables."
"The application does not use lookup secrets (such as recovery codes or one-time passwords). Authentication is handled via Clerk's OAuth flow, and API access is via persistent proxy keys. Clerk handles any OTP/recovery code functionality within its managed authentication flows."
"The application does not implement its own out-of-band authentication. Clerk manages all email verification and authentication codes, including automatic expiration. Google OAuth tokens have standard Google-defined expiration periods and are refreshed automatically by Clerk."
"All cryptographic random generation uses Node.js crypto.randomBytes(), which sources entropy from the OS-level CSPRNG. Proxy keys are generated with 256 bits of entropy (32 bytes). Clerk handles authentication code generation using its own CSPRNG implementation, which exceeds the 20-bit minimum."
"Session management is handled by Clerk. When a user logs out, Clerk invalidates the session token and clears all session cookies. The Clerk middleware validates session tokens on every request, rejecting expired or invalidated sessions. Proxy keys are independent of user sessions and must be explicitly revoked."
"Clerk provides built-in session management including the ability to view and terminate active sessions. When a password is changed through Clerk, the user can opt to sign out all other sessions. This functionality is part of Clerk's UserButton component integrated in our application layout."
"The application uses two authentication mechanisms: (1) User sessions - managed by Clerk via secure, HttpOnly session tokens. (2) API proxy keys (sk_proxy_*) - used by AI Agents for M2M authentication. These are static bearer tokens by design (agents cannot perform OAuth flows), but they support revocation, expiration, and fine-grained access rules."
"All dashboard operations (creating/revoking proxy keys, modifying access rules, managing delegations) require an active, valid Clerk session enforced by the auth.protect() middleware on all /dashboard routes. Clerk session tokens have finite lifetimes and are validated server-side on every request."
"All access control is enforced server-side in Vercel Edge Functions. The proxy handler performs multi-layered authorization: key validation, email access verification, delegation checks, and fine-grained rule evaluation. No access control logic exists in the client-side code."
"Access control data (proxy keys, access rules, delegations, email access mappings) is stored in PostgreSQL and can only be modified through authenticated dashboard API calls. The proxy handler reads these values directly from the database on each request. Users cannot manipulate access rules through the proxy API."
"The system enforces deny-by-default at multiple levels: (1) Proxy keys with no keyEmailAccess entries can access NO emails. (2) Send operations are denied unless an explicit send_whitelist rule exists. (3) Label blacklists and whitelists restrict readable emails. (4) Permanent deletion is globally blocked. (5) Email delegation requires explicit grant."
"The proxy handler wraps all logic in a try/catch block. Any exception results in a generic 500 Internal Server Error response. All authorization checks fail closed: if any check cannot be completed, the request is denied with an appropriate 401/403 error code."
"All database queries in the proxy handler are scoped to the authenticated user. Key lookups match the exact bearer token. Email access checks require both the specific key ID and target email in the keyEmailAccess table. Users cannot enumerate or access other users' keys, rules, or delegations."
"The application uses Google OAuth via Clerk as the sole authentication mechanism for administrative access. Google accounts inherently support MFA (2-Step Verification). There is no separate administrative interface - all users access the same dashboard with permissions scoped to their own data."
"The application uses Next.js built-in request parsing, which handles parameter parsing consistently. The proxy handler uses request.nextUrl.searchParams (standard URLSearchParams API) which automatically deduplicates parameters."
"The application does not directly interact with SMTP or IMAP servers. All email operations are proxied through the Gmail REST API (HTTPS). The proxy handler validates email addresses against access rules using safe-regex validated patterns. Outbound email send requests are validated against send whitelists."
"The application does not use eval(), Function(), or any dynamic code execution. Regex patterns from user-defined access rules are validated using the safe-regex library before compilation to prevent ReDoS attacks. The codebase has been audited with Semgrep."
"The proxy handler only forwards requests to a single hardcoded destination: https://www.googleapis.com/. The target URL is constructed by concatenating the fixed base URL with path segments - user input cannot redirect requests to arbitrary hosts."
"The application does not accept SVG uploads or process user-supplied SVG content. Previously existing unused SVG files (Next.js boilerplate) were deleted as part of our security hardening to eliminate potential XSS vectors."
"The application uses React (JSX), which automatically escapes all rendered content to prevent XSS. API responses are JSON-serialized using NextResponse.json(), which handles proper encoding. The proxy response body from Google is returned as-is without re-interpretation."
"All JSON handling uses JSON.parse() and JSON.stringify() - never eval(). API responses use NextResponse.json() which sets proper Content-Type with X-Content-Type-Options: nosniff to prevent MIME sniffing. React's JSX rendering automatically escapes all output."
"The application does not use LDAP. User authentication is handled by Clerk (OAuth/session tokens), and data storage uses PostgreSQL with Drizzle ORM's parameterized queries, which prevent SQL injection. No directory services are involved."
"User PII (email addresses, account metadata) is stored in Neon Serverless PostgreSQL, which encrypts all data at rest using AES-256. Google OAuth tokens are stored exclusively in Clerk's managed infrastructure (SOC 2 Type II certified). Gmail message content is never stored."
"Proxy key comparison is performed as a direct database query (WHERE key = $1), delegated to PostgreSQL's internal string matching. The application does not implement custom cryptographic comparisons. RSA key verification uses the jose library, which implements constant-time operations."
"All database primary keys are generated using PostgreSQL's gen_random_uuid() function, which produces GUID v4 using the database server's CSPRNG. Proxy keys are generated using Node.js crypto.randomBytes(). No predictable PRNG is used."
"Google OAuth tokens are stored exclusively in Clerk's managed token vault. Our application retrieves them at runtime via Clerk's server-side API and immediately uses them to authenticate with Google - never stored in our database or logged. RSA private keys are downloaded to the user's local machine and discarded from server memory."
"The application does not log proxy keys, OAuth tokens, or any credentials. Error logging uses generic messages without authentication details. The application does not process payment data."
"All API routes are marked force-dynamic, preventing Next.js/Vercel from caching responses. HTML pages use Cache-Control: no-store for authenticated content. Only public static assets are cached, and these contain no sensitive data."
"The application stores minimal data in browser storage. Clerk manages session state using secure, HttpOnly cookies not accessible to JavaScript. No proxy keys, access tokens, or sensitive information is stored in localStorage, sessionStorage, or IndexedDB."
"Proxy keys are sent exclusively in the Authorization: Bearer header. Session tokens are transmitted via Clerk's secure cookies. No sensitive data is transmitted via URL query parameters."
"All proxy requests are logged by Vercel's built-in request logging (timestamp, path, status code, response time). Database modifications are tracked via createdAt/updatedAt timestamps. Sensitive data values are never included in log entries."
"All connections use trusted TLS certificates: Vercel provides automatic TLS via Let's Encrypt. Database connections to Neon PostgreSQL require sslmode=require. API calls to Google use Google's publicly trusted TLS certificates. The Clerk SDK communicates exclusively over HTTPS."
"TLS certificate management, including OCSP stapling, is handled by our infrastructure providers. Vercel automatically manages certificate lifecycle and OCSP stapling for all hosted domains. Cloudflare provides additional OCSP stapling support. Neon PostgreSQL uses AWS-managed certificates."
)

echo "Starting SAQ fill - ${#yes_refs[@]} questions"

for i in $(seq 0 $((${#yes_refs[@]} - 1))); do
  q=$((i + 1))
  echo "Q${q}: Clicking Yes (${yes_refs[$i]})..."
  $CLI click "${yes_refs[$i]}" 2>/dev/null
  sleep $DELAY
  
  echo "Q${q}: Filling textbox (${text_refs[$i]})..."
  $CLI fill "${text_refs[$i]}" "${answers[$i]}" 2>/dev/null
  sleep $DELAY
  
  echo "Q${q}: Done"
done

echo "All ${#yes_refs[@]} questions filled!"
